/**
 * Repo Atlas — organize: renderers (pure).
 *
 * renderProjectsMd → the complete map, grouped by theme in config order with
 * `unsorted` last, then Outdated/ contents, then loose files. It never
 * truncates. renderClaudeBlock → the short agent-facing block between two
 * marker comments; spliceClaudeMd puts it into an existing CLAUDE.md
 * without touching the user's own lines. Part 2 (Task 7) adds the console
 * report.
 */

import { dayKey } from '../../shared/contract.js';
import { UNSORTED, themeNames } from './themes.js';
import { summarize } from './classify.js';

/** @typedef {import('./classify.js').ProjectRecord} ProjectRecord */
/** @typedef {import('./classify.js').Notices} Notices */
/** @typedef {import('./themes.js').OrganizeConfig} OrganizeConfig */

export const MARK_BEGIN =
  '<!-- atlas:begin — generated by `npm run organize` in repo-atlas. Edit projects.json, not this block. -->';
export const MARK_END = '<!-- atlas:end -->';

/** Rendered when a table cell has no value. */
const DASH = '—';

/**
 * @param {string|null} iso
 * @returns {string} local YYYY-MM-DD or 'unknown'
 */
export function fmtDay(iso) {
  return iso === null ? 'unknown' : dayKey(iso);
}

/**
 * @param {number} bytes
 * @returns {string}
 */
export function fmtBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB', 'TB'];
  let v = bytes / 1024;
  let i = 0;
  while (v >= 1024 && i < units.length - 1) {
    v /= 1024;
    i += 1;
  }
  const text = v >= 10 ? String(Math.round(v)) : v.toFixed(1).replace(/\.0$/, '');
  return `${text} ${units[i]}`;
}

/** @param {string} a @param {string} b */
function ciCompare(a, b) {
  return a.localeCompare(b, 'en', { sensitivity: 'base' });
}

/**
 * @param {ProjectRecord[]} records
 * @param {OrganizeConfig} config
 * @returns {Array<{ theme: string, records: ProjectRecord[] }>}
 */
export function groupByTheme(records, config) {
  const order = [...themeNames(config), UNSORTED];
  /** @type {Map<string, ProjectRecord[]>} */
  const buckets = new Map(order.map((t) => [t, []]));
  for (const r of records) {
    if (!buckets.has(r.theme)) buckets.set(r.theme, []); // theme only in overrides
    buckets.get(r.theme).push(r);
  }
  const groups = [];
  for (const [theme, list] of buckets) {
    if (list.length === 0) continue;
    if (theme === UNSORTED) continue; // appended last below
    groups.push({ theme, records: list.slice().sort((a, b) => ciCompare(a.name, b.name)) });
  }
  const unsorted = buckets.get(UNSORTED) ?? [];
  if (unsorted.length > 0) {
    groups.push({ theme: UNSORTED, records: unsorted.slice().sort((a, b) => ciCompare(a.name, b.name)) });
  }
  return groups;
}

/** @param {string} text */
function cell(text) {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/** @param {ProjectRecord} r */
function row(r) {
  const stack = r.stack.length > 0 ? r.stack.join(', ') : DASH;
  const remote = r.remote ?? DASH;
  const desc = r.description ?? '';
  return `| ${cell(r.name)} | ${r.kind} | ${r.status} | ${stack} | ${cell(remote)} | ${fmtDay(r.activityIso)} | ${cell(desc)} |`;
}

const TABLE_HEAD = '| Name | Kind | Status | Stack | Remote | Last activity | Description |\n|---|---|---|---|---|---|---|';

/**
 * @param {{ records: ProjectRecord[], notices: Notices, outdated: Record<string, string[]>, config: OrganizeConfig, nowIso: string }} input
 * @returns {string}
 */
export function renderProjectsMd({ records, notices, outdated, config, nowIso }) {
  const s = summarize(records);
  const unsortedCount = s.byTheme[UNSORTED] ?? 0;
  const out = [];
  out.push('# Projects', '');
  out.push(`Generated ${dayKey(nowIso)} by \`npm run organize\` (repo-atlas). Do not edit. Edit projects.json.`, '');
  out.push(
    `Summary: ${s.total} projects · ${s.byStatus.active} active · ${s.byStatus.paused} paused · ${s.byStatus.stale} stale · ${s.byStatus.empty} empty · ${s.byStatus.unknown} unknown · ${unsortedCount} unsorted`,
    '',
  );
  for (const g of groupByTheme(records, config)) {
    out.push(`## ${g.theme} (${g.records.length})`, '', TABLE_HEAD);
    for (const r of g.records) out.push(row(r));
    out.push('');
  }
  out.push('## Outdated', '');
  const subs = Object.keys(outdated).sort();
  if (subs.length === 0) {
    out.push('_(no Outdated folder yet)_', '');
  }
  for (const sub of subs) {
    const names = outdated[sub];
    out.push(`### ${sub} (${names.length})`, '');
    if (names.length === 0) out.push('_(none)_');
    for (const n of names) out.push(`- ${n}`);
    out.push('');
  }
  out.push('## Loose files at the root', '');
  if (notices.looseFiles.length === 0) out.push('_(none)_');
  for (const f of notices.looseFiles) out.push(`- ${f}`);
  out.push('');
  return out.join('\n');
}

/**
 * @param {{ records: ProjectRecord[], config: OrganizeConfig }} input
 * @returns {string} block including both markers, ending with a newline
 */
export function renderClaudeBlock({ records, config }) {
  const groups = groupByTheme(records, config);
  const themesLine = groups.map((g) => `${g.theme} (${g.records.length})`).join(' · ');
  return [
    MARK_BEGIN,
    '# ~/Projects',
    '',
    'Map of this folder: PROJECTS.md (generated, complete, grouped by theme).',
    '',
    `Themes: ${themesLine}`,
    '',
    'Archive: Outdated/archived-projects/ holds retired projects. Outdated/empties/ holds empty folders. Every move is logged in Outdated/MOVES.log.',
    '',
    'Rules for agents:',
    "- Each project's own README.md or CLAUDE.md is its entry point. Start there.",
    '- Do not create files at the root of ~/Projects. Work inside one project folder.',
    '- Do not move, rename, or delete project folders. `npm run organize` in repo-atlas does that, with confirmation.',
    MARK_END,
    '',
  ].join('\n');
}

/**
 * @param {string|null} existing current CLAUDE.md text, or null when missing
 * @param {string} block from renderClaudeBlock
 * @returns {string}
 */
export function spliceClaudeMd(existing, block) {
  if (existing === null) return block;
  const start = existing.indexOf(MARK_BEGIN);
  const end = existing.indexOf(MARK_END);
  if (start === -1 || end === -1 || end < start) {
    const sep = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
    return `${existing}${sep}${block}`;
  }
  const afterEnd = end + MARK_END.length;
  const tail = existing.slice(afterEnd).replace(/^\n/, '');
  return `${existing.slice(0, start)}${block}${tail}`;
}
